### ISSUE TITLE
Move download links from header to body?

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/fhir-bulk-data-docs#1]
Currently, generate file links are passed in an http Link header, per https://tools.ietf.org/search/rfc5988#page-6 . Some servers have an 8k limit on headers which may lead to failure in the case of long link urls and/or many links. 

Should we instead pass the links in the response body as ndjson? Perhaps something like:
```
{
  "_type": "Observation", 
  "href": "https://data/file/location/0001.Observation.ndjson"
}
```

This would respect the initial ```Accept: application/fhir+ndjson``` header by unifying the content types for the file list the files themselves. It would also let us include additional metadata down the road.

**Comment by jmandel** [comment]
Great question, and something that will only really come up when data sizes get large enough (or servers break them down into a large enough number of files). Let's try to push on this at the connectathon and see when/where servers break, as well as raising the question there.

**Comment by grahamegrieve** [comment]
I don't think that we'll push the 8k limit. And keeping things in the headers allows for a useful HTML body in case of client side errors

**Comment by jmandel** [comment]
One file per resource type x 50 characters per URL is already 5k chars. So this does seem like a looming limit.

**Comment by vlad-ignatov** [comment]
On my implementation I had to increase the limit to 32K and it is still easy to hit. Another reason for that is that those links must be full absolute URLs (or at least we should support that) so they often take more than 100 characters.

**Comment by jmandel** [comment]
>  I had to increase the limit to 32K

Was this a web server configuration change? Like, in an nginx config file, or a nodejs library, or something else?

**Comment by vlad-ignatov** [comment]
I use Node which either does not have any limit or it is very high. Severs like Apache, Nginx and others do have such limits typically >= 8k, but Node, being a lower level thing might not have one.

Another interesting aspect is that clients can also have similar limit. In my case Node was generous but if I query something like that with Ajax request in Chrome, the browser refuses to parse it after a certain limit (say 64k).

So, just to make sure I have some limit I did the following:
```js
if (Buffer.from(links).byteLength > 32 * 1024) {
    return res.status(413).send("Response headers too large");
}
```
This typically allows me to fit up to 120 files in the link header.

**Comment by plangthorne** [comment]
+1 to this suggestion. Philosophically, since it is the primary payload for the /bulkstatus endpoint, it seems most natural for this payload to be in the body of the response. Practically, moving this to the body allows the server to serialize the payload in a format with broad tooling support such as JSON.

**Comment by gotdan** [comment]
Moved links to json payload in body in v0.1
