### ISSUE TITLE
Support bulk data protocols on other FHIR requests

### ISSUE THREAD

**Issue by bvdh** [smart-on-fhir/fhir-bulk-data-docs#11]
The Async mechanism has advantages also for other requests and operations. Therefore I suggest that we broaden the scope of bulk data to include also other requests on the FHIR server. This will allow it to be also used in other time consuming or data heavy requests. Examples of those are retrieval of all resources of a type, evaluating measures and applying plan definitions.

Based on the current specification, you could split the spec up into the (semi-independent) patterns presented below.

**$export operation**
	The current bulk data spec uses the parameters _type and _sync, … These should become a regular operation on Patient.

**Trigger async response**
	This pattern triggers a async response of a GET request on the FHIR repo.
	The trigger for this would be the header: Prefer = respond-async.
	The result will follow the process as explained in the spec with the alternations discussed in the sections below.

**Retrieval format**
	The current spec only recognizes application/fhir+ndjson, I suggest we also support the normal json and xml export.

The last three concepts can be applied to all GET requests in FHIR and are, so far as I can see, compatible with the current FHIR spec.

**Comment by jmandel** [comment]
Agreed with this model; we'll be sure to separate the infrastructure from the use-case-specifics of patient/group export as we incorporate these details into FHIR.

**Comment by jmandel** [comment]
As we work through scope and content, we'll try to keep the number of files small. For the pieces that get incorporated directly into the FHIR spec, these will be modular as you've suggested (see http://build.fhir.org/async). I'm closing this issue for covered for now; let us know if there are any concerns!
