### ISSUE TITLE
Using the Group resource

### ISSUE THREAD

**Issue by mattkoch614** [smart-on-fhir/fhir-bulk-data-docs#13]
How might we effectively use the ``Group`` resource to support bulk export data? The example [here](https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/export.md#endpoint---group-of-patients) seems to pertain only to the ``Patient`` resource. What if we consider a use case where we are attempting to get a slice of lab results based on some grouping criteria?

The FHIR specification indicates that the ``Group`` resource has a ``member`` attribute, which I would assume is the location where an array of the actual data of interest would be housed (for example, a list of ``Observation``.)

https://www.hl7.org/fhir/group.html

The issue I see here is that [member.entity](https://www.hl7.org/fhir/group-definitions.html#Group.member.entity) represents data by reference - this would equate to a relative FHIR URL for each value. 

For example, given the following GET call:

``http://example.org/Group/12345/Observations``

We'd most likely get the following (some attributes omitted for brevity):

```
{
    "resourceType": "Group",
    "identifier": [
        {
            "system": "http://example.org",
            "value": "12345"
        }
    ],
    "member": [
        {
            "entity": {
                "reference": "http://example.org/Observations/1"
            }
        },
        {
            "entity": {
                "reference": "http://example.org/Observations/2"
            }
        },

    ...
    ]
}
```

Should we consider using the [Bundle](https://www.hl7.org/fhir/bundle.html) resource instead, which contains [Bundle.entry.resource](https://www.hl7.org/fhir/bundle-definitions.html#Bundle.entry.resource), allowing for an actual representation of the data?

**Comment by jmandel** [comment]
The intent of the `Group` resource in FHIR is to represent a group of Patients (or practitioners, or a couple of other types -- but mostly patients) who have certain characteristics in common. A FHIR `Group` isn't designed to store Observations or other clinical data. So the way we'd use Group in the bulk data export is as an entry-point for an export job: a shorthand for a subset of patients on whom we want to export data. The key examples we've heard to date would be things like:

* all the patients on a given insurance plan
* all the patients enrolled in a specific disease management plan
* all the patients enrolled in a specific trial

**Comment by mattkoch614** [comment]
Thanks for the clarification - this makes sense. This question probably speaks more to me being a FHIR newbie than anything.

**Comment by jmandel** [comment]
Sure thing! I'll close out this issue.
