### ISSUE TITLE
What are the EHR's obligations in validating an authorization JWT?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/fhir-bulk-data-docs#17]
Currently the spec leaves a TODO to define a server's obligations in validating a client's JWT. We should flesh this list out.

```
Servers SHALL

validate the signature on the JWT
check that the JWT exp is valid
check that the JWT aud matches the server's OAuth token URL (the URL to which the token was POSTed)
check that this is not a jti value seen before (prevention of replay attacks)
ensure that the client_id provided is known and associated with the supplied iss
```

**Comment by mspsullivan** [comment]
jmandel we refer to "client_id" in the suggestion for validation. Is the "client_id" always the same as the subject?
The validation language might be more clear if we mirrors the table earlier in the document titled "Authenticaion JWT Claims". This table could show the validation for each claim.

**Comment by daliboz** [comment]
We may want to source most of this/reference [RFC 7523](https://tools.ietf.org/html/rfc7523#section-3) directly.

**Comment by jmandel** [comment]
Closed by https://github.com/smart-on-fhir/fhir-bulk-data-docs/pull/46
