### ISSUE TITLE
Rename status response "secure" to be more precise

### ISSUE THREAD

**Issue by isaacvetter** [smart-on-fhir/fhir-bulk-data-docs#19]
The status response currently includes a boolean _secure_ element, which is intended to indicate to the client a requirement to authenticate with their backend services access_token when accessing a specific file of FHIR resources. 

The backend services access_token is intended to be short-lived and may have expired before files are ready to be downloaded. If an access_token is required, the client would need to re-request it.

While it's probably valuable to inform the client that they do need to use an access_token to access these files, there are a number of alternative security mechanisms in wide-spread use that would make the download of bulk PHI "secure" that would not involve an OAuth2 access_token. ([AWS's signed urls](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html) are a good example).

For these reasons, we should look at renaming this element from _secure_ to a word that more precisely describes the requirement for the use of an http Authorization header access_token.

**Comment by jmandel** [comment]
Discussion in [bulk-data#secure on zulip](https://chat.fhir.org/#narrow/stream/95-bulk-data/topic/secure.3A.20false.20.2E.2E.2E.20.3F): suggested `requiresAuthorizationToken`. I like it, too.
