### ISSUE TITLE
Allow clients to specify output target as part of export request

### ISSUE THREAD

**Issue by kurttheviking** [smart-on-fhir/fhir-bulk-data-docs#20]
Currently, the [server controls where to store export files](https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/export.md#response---complete-status) after they have been generated. However, we (myself and the other members of the GCP FHIR team) believe users and clients may want to control the destination target for the generated files. Specifically, controlling the destination allows users/clients to implement export retention policies, localization policies, additional access control policies, and so on.

So, for example, a client could say something like:

```
GET [fhir base]/Group/[id]/$export?destination=sftp://1.2.3.4/folder
```

Or...

```
GET [fhir base]/Group/[id]/$export?destination=d://path/to/network/folder
```

Or, in our case,

```
GET [fhir base]/Group/[id]/$export?destination=gs://bucket/folder
```

The FHIR Server would be responsible to describing and implementing supported destinations including whether or not there is a default destination (e.g. local) and the retention policy of that default.

Wht do others think? I tried to preserve backcompat with the default but perhaps that's less of an issue given the version status of the spec.

**Comment by jmandel** [comment]
We had something like this in our earliest design sketch, and took it out to focus the conversation.

Overall I'm open to this, though I'll note that it begins to blur the lines about whether these  ndjson URLs are intended as a standardized way for a client to obtain the data, vs. a way to directly put the content in a client-specified place. 

When it comes to retention policies, it's also important to explore the desired effects here. A client wouldn't generally be responsible for (or allowed to tweak) a server's internal infrastructure decisions, but of course it would be responsible for any what happens on "its own" side of the line. This propose effectively moves the line.

Beyond this, I think there *needs* to be well defined, working behavior when a client doesn't specify where any details, leaving the server to manage the handoff. (Separately on the subject of retention, we might also want to specify that if the client deletes an export job via `DELETE [polling content location]`, any exported files should deleted or make unavailable.)

**Comment by js8080** [comment]
I worry about this suggestion. As a FHIR server, it's my responsibility to make sure the data I'm sharing is shared in a secure manner. If I allow a client to give me an arbitrary location for storing that data, that feels very risky. How do I know that location is secure? It also feels like we're opening up the details of the server -- currently it's more of a black box but now you're letting the client control it's inner workings of where it stores files (and who says they're actually files on the backend and not database records or some other mechanism?).

I suppose I wouldn't have a problem with this if it was optional and the server had the ability to say "No, sorry I won't be saving the data there" and reject the request. But then that also expands the scope of the specification and we'd want to make sure the benefit was worth that.

With the currently spec'd approach, the FHIR Bulk Data Client can always retrieve the files and then save them wherever it wants and accomplish the same goals of "export retention policies, localization policies, additional access control policies, and so on" (right?)

**Comment by jmandel** [comment]
FWIW, I didn't hear Kurt's suggestion as suggesting that all server's would support *arbitrary* URLs. A server would determine the schemes and paths it supported.

**Comment by js8080** [comment]
Ah, good point. Missed that important detail. Still, the server would have to somehow come up with that curated list of destinations. _Something_ would still need to be responsible for knowing those locations are secure, etc. (a human?). It also still feels like inappropriately opening up the inner workings of the server and adding complexity. What if the server isn't creating files to store the resource data? The spec doesn't say it has to create files -- it just says the server has to support the File Request.

Also, I think the client can still accomplish this itself by requesting the files and saving them where it wants (as I mentioned above).

**Comment by gotdan** [comment]
I think @JustinStauffer makes a good point - it seems like a destination parameter would be very implementation specific to be part of the spec (particularly if you consider the different auth strategies that may or may not be supported for each of the potential storage endpoints). 

That said, as long as a server supports the specified url based access to the files, I don't see why it couldn't also allow a proprietary parameters to save directly to a specific storage location. To me this seems to be equivalent to providing a web based client that accepts the same parameters as the bulk data api, proxies the status responses, and then downloads the files into a bucket.

**Comment by kurttheviking** [comment]
> If I allow a client to give me an arbitrary location for storing that data, that feels very risky. 

To confirm @jmandel comment, I certainly didn't mean to imply arbitrary locations here and I apologize for the confusion. Instead, I meant pre-configured options for a destination with a given implementation stating what options it supports.

In my head, I attached this idea to is the comment ["Note: These files may be served by a file server rather than a FHIR specific server"](https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/export.md#file-requests). With this feature request, I'm trying to clarify how that could work where the client and FHIR server agree on a file server (or set of file servers) in advance. That file server may be a set of network drives, cloud buckets, etc.

>  It also still feels like inappropriately opening up the inner workings of the server and adding complexity.

The core of my argument I suppose rests not on whether we're adding/removing complexity, but where that complexity should sit. I agree that a `destination` involves more API surface and implementation work but relieves work with respect to persistence and access control of the files after being generated. For some additional context, the use case I am working from is a FHIR endpoint that is serving hundreds of thousands to millions of these exports per day while also respecting locality requirements and retention policies of any "exported" data.

> What if the server isn't creating files to store the resource data? The spec doesn't say it has to create files -- it just says the server has to support the File Request.

That's true. Again, I am thinking if someone does `Group/:id/$export` on a group of 10M patients, it's unlikely the FHIR server can hold that in memory and, moreover, it's a sufficiently long running operation that a target file becomes a resource-efficient way to generate the output.

> It seems like a destination parameter would be very implementation specific to be part of the spec (particularly if you consider the different auth strategies that may or may not be supported for each of the potential storage endpoints).

Very true. And, to be clear, I certainly don't expect every implementation to add every possible protocol and destination. In fact, I very much like the default the way it is in the spec today. But, implementations could add things like "deliver this payload to a webhook" through an `http` destination would could alleviate polling chatter if that's something of concern to the FHIR server in question.

> That said, as long as a server supports the specified url based access to the files, I don't see why it couldn't also allow a proprietary parameters to save directly to a specific storage location. 

Yes, that was my thinking as well.

**Comment by gotdan** [comment]
@kurttheviking Given that different servers are likely to vary in the destination information they require (eg. different credential and config parameters), perhaps one way to address this use case would be to include language in the spec to the effect that implementations can optionally support additional parameters on the kickoff request as long as they also support requests without those parameters? That way, a client that wishes to work across servers could be confident in the ability to download the bulk data files and upload them into a bucket, while a client that is server specific could supply the destination bucket information as part of the request.

**Comment by kurttheviking** [comment]
@gotdan I see what you're saying -- I think the part that's difficult at scale is "as long as they also support requests without those parameters". For instance, we have an export that has hundreds of millions of resources and, as a result, is quite large. With lots of API consumers asking for large payloads (potentially erroneously -- e.g. an accidental cron job), it's not feasible to internally maintain the results. Moreover, the entity originating the request may have specific retention or locality requirements for any exported data and they don't have a way to tell the API to enforce those concerns.

So, my solution is to push that decision onto the API consumer and the API implementation. Again, this would be completely optional. If an implementation is expecting relatively light loads, then this might not be an issue and they don't need to support it. However, an API *CAN* require a `destination` parameter to allow the clients to specify where to put the exports once finalized.

**Comment by jmandel** [comment]
Regarding the particular questions of data locality or retention expectations: isn't it fair to say that the FHIR server is _already_ storing data in some appropriate fashion? i.e., it has a way to meet regulatory requirements, and in the absence of further guidance could just follow those same policies?

**Comment by kurttheviking** [comment]
@jmandel yes, that's true from a regulatory perspective; I'm speaking more for organizational policies which differentiate between the data in the primary store (e.g the FHIR API) and data extracted from that API and put in other places...especially when it comes to retention policies. Those may not necessarily be the same team and, more complicated, vary base on who or what application requested the export.

I think what drives this is the fact that the API needs to do something with the export results and it's not feasible to keep them in the "API" (which, under the hood, is an arbitrary number of instances) so we want to ask API consumers to tell us where to put them.

**Comment by jmandel** [comment]
This is interesting. The fundamental concern is that *requiring* special target parameters means you can't have a generic client. Instead, a client *must know* details specific to GCP (or whatever), even if it doesn't want to, or can't reasonably be expected to.

These clients of course are going to be responsible for implementing appropriate data handling, retention, management, etc *once they've received the data* -- but I'm not sure it's feasible for them to be forced into responsibility for guiding server behavior *prior to the handoff*. (If the requirements are really about locality and retention, and we think they're generalizable, maybe we should directly model parameters like `&need_locality=EU&need_expiration=3days`.)

**Comment by kurttheviking** [comment]
@jmandel That's a fair point &ndash; my intent was to provide support for a generic client and I don't want to propose breaking that aspect. One option would be for an implementation to make this a configuration of the API itself. For example, GCP (again, or HAPI, or whatever) could move the `default_destination` out of the API request flow itself and into the equivalent of a config file. Thus, one could satisfy the generic client requirement because a default was provided during setup while still enabling changes to that default via the API.

**Comment by gotdan** [comment]
@kurttheviking @jmandel I like the idea of moving destination information into the server config (possibly with optional override by query string params). To me, this seems like the right separation of concerns and would both support generic clients and allow server providers to support complex configuration (max bucket size, retention duration, bucket naming conventions, etc) in a straightforward way.

**Comment by kurttheviking** [comment]
@gotdan works for me; is there anything you need (e.g. a PR) to help move this into the spec? e.g. is `destination` the only param or should we expect more/generic params?
