### ISSUE TITLE
Use of "Expires" header in Complete Status response

### ISSUE THREAD

**Issue by js8080** [smart-on-fhir/fhir-bulk-data-docs#24]
Hey folks, I was wondering if it's really appropriate to use the "Expires" HTTP header in the "Complete" status response to indicate when the results will expire.

After digging into this a bit for our implementation of a FHIR Bulk Data service, I realized the "Expires" header is actually part of the HTTP Cache-Control which deals with caching of web responses.

I won't proclaim to be an expert in HTTP but it seems like we're misusing this header for something it wasn't quite intended for and instead, it may be better to actually put the expiration date of the files within the actual JSON body of the response (along with the file URLs, etc.)

Does anyone have thoughts on this one way or the other?

**Comment by jmandel** [comment]
I don't feel strongly about this, but the semantics of `Expires` seem to do an okay job to me of communicating "After this time, the resource will be stale"; it's an effective hint, without being a guarantee that the resources will disappear.

**Comment by js8080** [comment]
Yeah, I just wasn't so sure about it initially and thought we may be expanding the intended scope of this header value and misusing Cache-Control. But it's no big deal -- I just wanted to run it by others to see if it was a concern. If others are OK with it, I'm fine closing this.
