### ISSUE TITLE
Specify "Accept: application/json" for polling request

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/fhir-bulk-data-docs#25]
Should clarify that a client should supply `Accept: application/json` for a polling request.

See discussion at https://chat.fhir.org/#narrow/stream/95-bulk-data/subject/Cologne.20Connectathon/near/148990

**Comment by js8080** [comment]
"should supply" or "shall supply"?

**Comment by gotdan** [comment]
Resolved with #35
