### ISSUE TITLE
What are the requirements around the issuer URL, what is it used for?

### ISSUE THREAD

**Issue by daliboz** [smart-on-fhir/fhir-bulk-data-docs#26]
Are there requirements we should define for the issuer URL? Initial thoughts:

- https?
- Recommended methods to confirm domain is owned by the consuming application?
- absolute URL?

This is also a bit artificial right now - the issuer doesn't currently serve a purpose if the client id is going to be assigned. We **could** use the issuer URL to help bootstrap trust. EG: A model where the consumer / client offers an https:// endpoint as their “issuer URL”, the EHR then discovers their JSON Web Keys from that URL (for example, at ./.well_known/smart_client_keys). The issuer could replace the client id concept (or it could exist in the background but may not be used in practice) and no longer require registering public keys (and headaches associated with rotation and revocation…).

One of the concerns we've discussed with this approach is how this would work with off the shelf OAuth servers.

**Comment by jmandel** [comment]
Reviewing our discussion up to this point, here's what I'd like to propose.

## The goals are:

* Maintain compatibility with off-the-shelf OAuth server behavior
* Maintain consistency with JWK headers used in CDS Hooks
* Avoid "magic" (special constants) in mapping issuers to JWKS URLs
* Don't assume that all clients are online and can host web content
* Enable what we hope will be the common case of online clients that routinely rotate their keys

---

## Registration + Runtime
1. At registration time, the client supplies:
b. (OPTIONAL) a JWKS URI that the server should consider "whitelisted" for use with this client. This URL may later appear in the `jku` of a JWT presented by the client.  Servers may choose to perform some kind of domain ownership assessment on this URI.
c. (OPTIONAL) a JWKS directly -- that is, a static keyset supplied at registration time.

2. At registration time, the server assigns a `client_id` which the app must use when issuing requests. This *may be* the same as the Issuer URN, but it need not be. To the client, it's opaque.

At request time, the client creates a token request using:
* `client_id` assigned at registration, to maintain compatibility with https://tools.ietf.org/html/rfc7523 and to account for use cases where a single issuer might actually want to register multiple clients.
* An authentication whose JWT payloads includes `iss`  and `sub` claims (both of which are always set to the client_id) and whose header includes:
  * (REQUIRED) `alg`: id of the key used to sign this request
  * (REQUIRED) `kid`: id of the key used to sign this request
  * (REQUIRED) `type`: id of the key used to sign this request
  * (OPTIONAL) `jku`: JWKS URL pointing to a key set that includes the key used to sign this token. 

(Note this list of header fields matches what we've settled on in CDS Hooks, as well.)

## Verification algorithm

To resolve a key to verify signatures, a server follows this algorithm:
1. If `jku` is present, verify that the `jku` is on the JWKS URL whitelist for the specified `client_id`.
a. If the `jku` is not on the whitelist, the signature verification fails.
b If the `jku` is on the whitelist, create a set of potential keys by dereferencing the `jku` URL. Proceed to step 3.
2. If `jku` is absent, create a set of potential key sources consisting of: all keys found by dereferencing the registration-time JWKS URI + any keys supplied in the registration-time JWKS. Proceed to step 3.
3. Filter the potential keys to exclude any where the `alg` and `kid` do not match the values supplied in the client's JWK header.
4. Attempt to verify the JWK using each key remaining in the potential keys list.
a. If any attempt succeeds, the signature verification succeeds.
b. if all attempts fail, the signature verification fails.

**Comment by jmandel** [comment]
@daliboz thanks for your offline comments! I've updated the proposal above based on our conversation yesterday. Reviewing existing dynamic registration protocols, I'm less and less convinced of the benefit of making the client generate an `iss` for our use case here -- and more and more convinced by your argument that we can drop it. So I've dropped it above, and documented that the `iss` and `sub` from our JWT payloads should both be set to the client id. Thoughts?

**Comment by jmandel** [comment]
I know you've been busy @daliboz -- would love to wrap this up when you have a chance to review :-)

**Comment by jmandel** [comment]
We should mention in the spec, explicitly, that via the `jku` approach clients will be able to rotate their own keys.

**Comment by whitehatguy** [comment]
> So I've dropped it above, and documented that the iss and sub from our JWT payloads should both be set to the client id. Thoughts?

+1

**Comment by jmandel** [comment]
Closed by https://github.com/smart-on-fhir/fhir-bulk-data-docs/pull/46
