### ISSUE TITLE
Token Expiration too long

### ISSUE THREAD

**Issue by daliboz** [smart-on-fhir/fhir-bulk-data-docs#27]
The current specification calls out a 15 minute expiry, though OAuth 2 recommends that tokens live no longer than 10 minutes. In addition, the SMART specification even recommends 5 minutes. I assume we would want 10 or less before expiry.

**Comment by jmandel** [comment]
Agreed that we should update our spec to clarify guidance. Re: the "10 minute" number, can you share a reference for this? (I see that https://tools.ietf.org/html/rfc6749#section-4.1.2 recommends 10 minutes for the `code` in an authorization code flow, but I may be missing a recommendation from elsewhere about token lifetimes.)
