### ISSUE TITLE
Recommendations around error handling

### ISSUE THREAD

**Issue by daliboz** [smart-on-fhir/fhir-bulk-data-docs#28]
The current backend services specification doesn't call out how servers should handle errors. We should add some requirements around what types of errors are expected and any recommendations. For example, we've used the error_uri (from OAuth) in our responses which help provide human readable error responses (and allows for localization).

**Comment by jmandel** [comment]
@daliboz Do you want to propose some specific language here?

**Comment by daliboz** [comment]
I created PR #53 - let me know what you think.

**Comment by jmandel** [comment]
I like this! A quick example would help, too!
