### ISSUE TITLE
Tools and References sections?

### ISSUE THREAD

**Issue by daliboz** [smart-on-fhir/fhir-bulk-data-docs#29]
We should move the tools out of the core part of the specification. We could do this a few ways, by providing references to them in a summary or abstract, or by having a section that references them.

We should have a references section that links to prerequisite specifications (OAuth 2, JWT, etc). 
In addition, we should try to defer to these specifications when discussing specifics (eg: how to validate a JWT) since they're the authoritative source.

**Comment by jmandel** [comment]
Thanks! 

+1 on moving the tools out into their own page. When it comes to deferring to existing specs, I totally agree from a formal / "normative" perspective. It can still be helpful to call out examples of the kinds of things that developers need to keep in mind, even if we say "for full requirements refer to [ref]".

If you're willing to put together a PR with the changes proposed here, I think we'd be in a good position to merge.

**Comment by gotdan** [comment]
@daliboz I moved the tools onto their own page to address this issue. Also, I agree that it makes sense to include links to relevant specs when they're referenced in the documentation. Are there any specific ones that you'd like to add now, or should we just keep this in mind and plan to incorporate them as they come up in discussion?

**Comment by jmandel** [comment]
@daliboz we'll close this as addressed, but feel free to open up specific issues about referencing additional specs as needed!
