### ISSUE TITLE
How to retrieve data not tied to an individual patient

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/fhir-bulk-data-docs#3]
How should we handle data global entities like organizations?

**Comment by jmandel** [comment]
(Piling on here: Concept Maps, too, which support vocab/code mapping -- these files can get big, and can be very tailored to a specific institution.)

**Comment by gotdan** [comment]
Added the following language to v0.1:

Only resources of the specified resource types(s) will be included in the response. If this parameter is omitted, the server should return all resources in the Patient Compartment as well as resources that are helpful in interpreting the patient data such as Organization and Practitioner.
