### ISSUE TITLE
Define expectations for rate limiting on polling requests

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/fhir-bulk-data-docs#30]
From May Connectathon:

* Throttling while polling
  * we should have consistent error codes (e.g. 429 status code for "too many requests")
  * We need to test the currently defined approach with "Retry-After" header containing a http date or a delay time in seconds
  * Should servers prevent client new exports while a previous request is running?

**Comment by gotdan** [comment]
With regard to the question of "Should servers prevent client new exports while a previous request is running?", we could note in the spec that a server may return a [503 Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) and optionally a Retry-After header in response to the bulk data request.

**Comment by jmandel** [comment]
Two conditions where we can provide advice:

* If a client is polling too fast: error code ==  `429`, with a `Retry-After` and optionally an OperationOutcome
* If a server wants to prevent a client from beginning a new export before the current one is done == `429`, with a `Retry-After` and optionally an OperationOutcome
