### ISSUE TITLE
Define system-wide $export

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/fhir-bulk-data-docs#31]
Our Argonaut use cases have focused on exporting data about groups of patients. There are also bulk export use cases for non-patient-related resources like:

* Export all resources from a server (e.g., for backup / snapshots)
* Export all resources of a particular type (e.g., "terminology data export)

We can handle these nicely by defining a system-level export like:

```
GET [base]/$export?_type=CodeSystem,ValueSet
```

**Comment by jmandel** [comment]
@grahamegrieve @kurttheviking FYI

**Comment by kurttheviking** [comment]
@jmandel makes sense; is the all resources version of this (first bullet) `GET [base]/$export` &ndash; e.g. no query param.

**Comment by jmandel** [comment]
Yes -- by default, all resource types
