### ISSUE TITLE
How should a server represent errors to the client?

### ISSUE THREAD

**Issue by isaacvetter** [smart-on-fhir/fhir-bulk-data-docs#32]
For the bulk data API, let's consider a request for resources for 10k patient records. 

Naturally, some errors may occur during data retrieval.  We want to communicate these errors to the bulk client. 

One way to report errors, where a small subset of resources are unavailable, could be to return an OperationOutcome .ndjson file with OperationOutcome.issue.location used to identify the patient whom this applied to. 

Isaac

**Comment by jmandel** [comment]
TODO: PR adding total resource counts and error counts to our response payload, and describing any expectations on `OperationOutcome` contents.

**Comment by isaacvetter** [comment]
Talked through this on the Argonaut call.

Yes, it makes sense to include one or more files of OperationOutcomes encountered during the export operation.

Further, we discovered the possibility of adding optional resource counts per file in the status response.

Lastly, Josh pointed out the edge case of a FHIR server exporting OperationOutcome resources which were stored within the FHIR server, and not generated as part of the export operation. How can we differentiate between these scenarios?
