### ISSUE TITLE
Renamed requiresAccessToken to requiresAccessToken

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/fhir-bulk-data-docs#59]
At the very last line of https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/export.md (the change log) it says "Renamed `requiresAccessToken` to `requiresAccessToken`". The `requiresAccessToken` word is the same in both places.

**Comment by jmandel** [comment]
Thanks! Fixed in #60.
