### ISSUE TITLE
URL Operation Conflict

### ISSUE THREAD

**Issue by jawalonoski** [smart-on-fhir/fhir-bulk-data-docs#6]
`Patient/$everything` is already an established operation.

How about an alternative of `/$bulkdata` (a system-level operation) or if you want the operation "compartmentalized" within established FHIR compartments: `Group/[id]/$bulkdata`

**Comment by gotdan** [comment]
I agree about the name - in particular I think it's confusing to have one ```$everything``` operation that supports async and one that does not. What about a ```$export``` operation that would work on compartments (and requires support for async and ndjson)?

We could have ```Patient/$export```, ```Group/[id]/$export```, etc

**Comment by jawalonoski** [comment]
Looks like this has been resolved to `$export`
