### ISSUE TITLE
Clear the authorization docs

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/fhir-bulk-data-docs#61]
While trying to implement the latest auth spec, I encountered several problems. They might be an issue or maybe the descriptions are just not clear enough. I will submit those as comments below:

**Comment by vlad-ignatov** [comment]
After reading the dogs, I got the impression that the RSA SHA-256 algorithm is deprecated but the diagram still shows "RSA SHA-256" for signing.  The text below the diagram contains  "The authentication JWT is constructed with the following claims, and then signed with the backend service's private RSA key **(RSA SHA-384 signature)**".

I find this confusing. Either the image should be corrected, or we should be more explicit that other algorithms are also allowed for signing the token.

**Comment by jmandel** [comment]
This is a diagram error. Thanks for pointing it out!

**Comment by jmandel** [comment]
Can you please submit other problems as separate issues @vlad-ignatov? We'd like to track and fix discretely.
