### ISSUE TITLE
Can a service have registration-time JWKS URI but not provide a jku header?

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/fhir-bulk-data-docs#63]
In this section https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/authorization.md#server-obligations-for-signature-verification, it is said that:

"If jku is absent, create a set of potential key sources consisting of: **all keys found by dereferencing the registration-time JWKS URI** + **any keys supplied in the registration-time JWKS**. Proceed to step 3."

In my implementation, an app is registered either with JWKS or with JWKS URL (but not both). If the app has a JWKS URI, its token header contains `jku`. Otherwise it does not and uses JWKS instead.

It appears to me that the two bold parts above should be joined with `or` instead of `+`, because I can't have both of them? I am not sure about this though. Perhaps I have not understood it correctly?

**Comment by jmandel** [comment]
Thanks for checking about this. The way we've written the spec, a servers would permit apps to register either a JWKS *or* a JWKS URI at registration time. At runtime, let's call 
a)  all keys found by dereferencing the registration-time JWKS URI
b) any keys supplied in the registration-time JWKS

The union of (a) and (b) will be empty on one side, but it's still technically a union.

Do keep in mind that the `jku` parameter is optional, so it's technically valid for an app to register a JWKS URI at registration time, and then omit the `jku` from signed payloads. Your implementation should ideally work even in this case. Does this make sense?

**Comment by vlad-ignatov** [comment]
Yes, that is what I though. Do you think it can be a little clearer? Perhaps if `a)` also begins with `any`?

**Comment by jmandel** [comment]
Cool, I like that -- proposed a PR for your review.
