### ISSUE TITLE
Notes about the JWKS structure 

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/fhir-bulk-data-docs#64]
Perhaps we can add a sentence or two to state that:
1. Services should not include private keys in hosted JWKS.
2. Public and private keys (pairs) in JWKS should have the same `kid`.

It is already mentioned between the lines but it takes some time to "discover" it:

kid | required | The identifier of the key-pair used to sign this JWT. This identifier MUST be unique within the backend services's JWK Set.
-- | -- | --

jku | optional | The URL to the JWK Set containing the public key(s). When present, this should match a value that the backend service supplied to the EHR at client registration time.
-- | -- | --

https://tools.ietf.org/html/rfc7517#section-4.5 is also not very clear about `2`.

I understand that this is not exactly in the scope of this spec, but it would make a big difference for the reader.

**Comment by jmandel** [comment]
For (1), I think that makes sense. For (2), I'm not sure why we'd say anything about private key ids if we just said in (1) that we don't expect private keys to be exposed/shared at all. Does this make sense? If so, would you be willing to propose a PR for (1)?

**Comment by vlad-ignatov** [comment]
You are right about (2) - we can do without it.
My use case was that my app works with the full JWKS that can in theory hold multiple pairs. Then I have to find the last private key that does have a corresponding public key (associated by kid) and use it for signing and `kid` header. In other words, from the server's perspective it does not matter but clients still have to deal with it.

**Comment by jmandel** [comment]
OK. I'm still not totally sure I understand the point here, but I think we have ended up at a good place. 

To re-state: clients only expose their public keys in JWKS, not full keypairs. Internally clients may be storing private keys wherever/howerver they (securely) choose.

**Comment by aviars** [comment]
Yes sounds right to me. While a no-brainer, its worth being explicit about not publishing private keys / only public keys.

**Comment by jmandel** [comment]
Perfect. I think @vlad-ignatov will propose a PR.
