### ISSUE TITLE
References between resources

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/fhir-bulk-data-docs#69]
I don't see anything in the specs about references between resources. 

The test data from the SMART reference server has resources ids set to GUIDs and the corresponding references using `urn:uuid:<guid>` - is this normative?

**Comment by jmandel** [comment]
Thanks! This  behavior doesn't look valid to me. (There are some rules for resolving references within a Bundle based on matching a referenxe to a Bundle.entry.fullUrl property -- but here we do not have a Bundle).

**Comment by michelemottini** [comment]
...what's the valid behavior? Or in other words, how should references between the resources obtained from a bulk request be expressed?

(Maybe this is in the specs and I am not seeing it? It won't be the first time...)

**Comment by jmandel** [comment]
I'm not sure we've stated this explicitly. The expectation is that these references should be relative uris, or absolute uris rooted in the base url for the server from which the export was performed. This is probably something we should talk through at the Connector phone to see if these guidelines failed to meet anybody's use case :-)

@gotdan

**Comment by michelemottini** [comment]
How do you resolve a relative (or absolute) uri to a specific line (or resource) inside a ndjson file?

**Comment by jmandel** [comment]
I'm interested to hear the examples of things that you might think are ambiguous. I haven't given this deep thought, but the rough algorithm that I have in my head is 

1. For relative references: you treat all resources that you have received from the export, and all relative references, as if they are relative to the exporting server's base URI. (For absolute references, you only can resolve them locally if they start with the exporting server's base URI; 
in which case, strip that prefix and proceed as though you had a relative reference.)

2. Given a reference like `Patient/123`, you look through all of the ndjson files returned where type=Patient, and scan for a resource with Patient.id==123.


(In practice, most downstream uses would put the received data into some kind of a data structure that makes this operation faster than a linear scan.)

**Comment by michelemottini** [comment]
OK, this is clear and answer my question: the reference URLs must end in `<type>/<id>` of the referenced resource.

And yes, if this is the case then the data returned by the SMART reference server is wrong:

`{ . . . "patient":{"reference":"urn:uuid:a6f0e6d2-8f94-43c0-94bf-cbf3986ece03"}, . . .,"resourceType":"AllergyIntolerance"}
`

`{"id":"06eb35fc-09e6-48b4-a311-47633f6c4769", . . .,"resourceType":"Patient"}`

**Comment by jmandel** [comment]
Agreed!

**Comment by michelemottini** [comment]
I am leaving this open because I think it warrants a mention in the specs

**Comment by vlad-ignatov** [comment]
The SMART Bulk-data server now returns references as `<type>/<id>`.

As for how you resolve them, I have always considered the downloaded files some kind of intermediary state. You would probably not have to resolve any references before inserting the data into another system (like another fhir server or a proprietary database).
