### ISSUE TITLE
Missing referenced resources

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/fhir-bulk-data-docs#70]
More a question than an issue: is the expectation that all referenced resources should be part of an export set? Or is it admissible that some exported resources references resources that are not in the export set?

If it is the latter - what is the client supposed to do with those references? Try to access directly the server to get that data? ...that could generate a ton of traffic....

(I am asking because the SMART test server export Encounter referencing Organization that are not in the export set, and the Cerner server exports Condition referencing Encounter that are not in the export set)

**Comment by jmandel** [comment]
What we say in the spec is:


> Only resources of the specified resource types(s) will be included in the response. If this parameter is omitted, the server should return all supported resources that the client has authorization to access and that the relevant business agreements allow. The Patient Compartment should act as a point of reference for recommended resources to be returned as well as other resources outside of the patient compartment that are helpful in interpreting the patient data such as Organization and Practitioner.

Would be great to have your thoughts on this. But the bottom line is that there is no built into equivalent of `_include=Encounter:organization` today.

**Comment by michelemottini** [comment]
Thanks Josh - I should have re-read the specs more carefully.

As a client writer I'd like to have all the reference resolve in the exported data set - as a server writer I can see some issues implementing that. 

I'd say that the specs are good as they are: unresolved references are possible and clients have to deal with them (but I'd point out for Cerner that Encounter _is_ in the Patient compartment...)
