### ISSUE TITLE
Non-Patient Compartment Resources

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/fhir-bulk-data-docs#8]
Do we need to specify which non-patient resources (like Practitioner and Organization) should be included in the $export requests if the _type parameter isn't supplied or should we leave this to the discretion of the server implementation (which may be more realistic in real world implementations)

**Comment by jmandel** [comment]
Current state talks about "use case applicable" resources -- I appreciate the update from @dkfriend07 to indicate the need for flexibility here. Though I wonder if we can avoid introducing the idea of client-specific use cases in the spec here. (Of course, individual clients may be authorized to retrieve only a limited subset of data!)

**Comment by gotdan** [comment]
Good point! @dkfriend07 @jmandel - what if we change "use case applicable" to something like the language we use earlier in the document: "[resources] the client application has security/authorization to view"?

**Comment by thedoglady** [comment]
@gotdan @jmandel Good point. I like the idea of coming back to authorization. I think it is also worth adding something to captures the broader level of why choice of resources is needed (BAA, privacy, performance) - maybe something like: "..If this parameter is omitted, the server should return all supported resources that the client has authorization for and that the business agreement allows."

Just an idea., maybe just saying "security/authorization" is broad enough on its own...

**Comment by gotdan** [comment]
Closing this issue since we're addressing resource sets for specific use cases in #16
