### ISSUE TITLE
[Question] How do you surface the markdown files?

### ISSUE THREAD

**Issue by mattkoch614** [smart-on-fhir/fhir-bulk-data-docs#91]
I am wondering how you display the source controlled markdown files (that will eventually make up a full fledged implementation guide) contained in this repo? I think source controlling them here is a great idea - curious to know if there is a web hook or similar process to ingest and host them once changes are merged, etc.

**Comment by jmandel** [comment]
Today we just point people at the GitHub repository with links like https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/export.md and https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/authorization.md .

Eventually I expect we will publish a standalone static website including this content, but right now we are more focused on getting the content right :-)

Would love to know if this causes any issues for you; we hope it is a pragmatic and lightweight approach for the time being.

Please note that I'm going to close this issue now, but will continue to pay attention if you want to follow up in comments!

**Comment by mattkoch614** [comment]
Awesome, thanks for this. GitHub makes a lot of sense as a platform to collaborate on something like this, especially because of the ability to leverage pull requests as a part of the review process. I think you're right to focus on getting the content right first. 

I am a member of a fairly large effort to author an implementation guide for clinical research, and have been mulling over strategies to get folks engaged in the conent writing while at the same time making that content readable. Perhaps I too should focus on the content first - a lot of editors these days have markdown preview tools built in!

🙂
